# Generated by Django 3.1 on 2020-12-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_categorymaster_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaster',
            name='parent_category',
            field=models.IntegerField(),
        ),
    ]
