# Generated by Django 3.1 on 2020-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201202_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaster',
            name='parent_category',
            field=models.CharField(max_length=20),
        ),
    ]
