# Generated by Django 3.1 on 2020-12-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201202_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymaster',
            name='parent_category',
            field=models.IntegerField(),
        ),
    ]
