# Generated by Django 3.1 on 2020-12-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201202_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymaster',
            old_name='category_description',
            new_name='category_type',
        ),
    ]
