# Generated by Django 3.1 on 2020-12-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201202_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaster',
            name='categorized_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category_mprouser', to='application.mpro_user'),
            preserve_default=False,
        ),
    ]
